### ISSUE TITLE
Incorrect error message is printed when the second argument to fork is missing

### ISSUE THREAD

**Issue by tetsuo** [fluture-js/Fluture#246]
CodE:
```
Future.of(1).fork(err => console.log(err))
```

Error thrown:

```
TypeError: Future#fork expects its first argument to to be a Function
  Actual: undefined
    at typeError (/Users/onur/tmp/node_modules/fluture/index.js:87:9)
    at invalidArgument (/Users/onur/tmp/node_modules/fluture/index.js:91:3)
    at Resolved.Future$fork [as fork] (/Users/onur/tmp/node_modules/fluture/index.js:428:24)
```

Missing argument is the second one not first.

**Comment by Avaq** [comment]
This was fixed here in https://github.com/fluture-js/Fluture/commit/9d07be2c3c3b431e31edd3455d702ce40fb69ba6#diff-7eb52b366866677666470e019283c8eaR132, but hasn't made it into a release yet due to breaking changes.
